apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: myapp
spec:
  storageClassName: manual   # db-pv.yaml ke storageClassName se match hona chahiye
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
