apiVersion: v1
kind: Secret
metadata:
  name: fileforge-secrets
  namespace: fileforge
type: Opaque
data:
  mongo-root-username: bW9uZ28tcm9vdC1hZG1pbg==
  mongo-root-password: Um9vdFBhc3MxMjMh
  mongo-app-username: ZmlsZWZvcmdlLWFwcC11c2Vy
  mongo-app-password: QXBwUGFzczQ1NiE=
  jwt-secret: MVhsU1VuRE9hQ3R5Q0tyVXRzNlRxNWsxaXNVVUwwNDBRT3N5SXhrLzZvWVpON0hwTDNxd0R5VElXNytMcHdwZAo=
